import { Metadata } from 'next';
import projects from '@/data/projects';
import ProjectCard from '@/components/ProjectCard';

export const metadata: Metadata = {
  title: 'Projects | Mitko',
  description: 'Generated by create next app',
};

const page = () => {
  return (
    <div className='text-white grid md:grid-cols-2 gap-x-6 gap-y-1'>
      {projects.map((project) => (
        <ProjectCard
          key={project.title}
          title={project.title}
          description={project.description}
          imgUrl={project.imgUrl}
          seeCode={project.seeCode}
          liveSite={project.liveSite}
          tech={project.tech}
        />
      ))}
    </div>
  );
};

export default page;
