import Navbar from "@/components/Navbar";
import "./styles/tailwind.css";
import localFont from "next/font/local";
import { Metadata } from "next";

const kaisei = localFont({
  src: "../public/fonts/kaisei-tokumin-latin-700-normal.woff2",
  weight: "700",
  variable: "--font-kaisei",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mitko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={kaisei.className}>
      <body className="bg-[#111010] px-4 py-12 flex flex-col md:flex-row max-w-4xl mx-4 md:mt-20 lg:mt-32 lg:mx-auto gap-12">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
